In [1]:
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
df=pd.read_csv("Heart.csv")
df

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [3]:
df=df.drop(columns="Unnamed: 0")
df

Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  \
0     63    1       typical     145   233    1        2    150      0   
1     67    1  asymptomatic     160   286    0        2    108      1   
2     67    1  asymptomatic     120   229    0        2    129      1   
3     37    1    nonanginal     130   250    0        0    187      0   
4     41    0    nontypical     130   204    0        2    172      0   
..   ...  ...           ...     ...   ...  ...      ...    ...    ...   
298   45    1       typical     110   264    0        0    132      0   
299   68    1  asymptomatic     144   193    1        0    141      0   
300   57    1  asymptomatic     130   131    0        0    115      1   
301   57    0    nontypical     130   236    0        2    174      0   
302   38    1    nonanginal     138   175    0        0    173      0   

     Oldpeak  Slope   Ca        Thal  AHD  
0        2.3      3  0.0       fixed   No  
1        1.5      2  3.0      normal  Yes  
2        2.6      2  2.0  reversable  Yes  
3        3.5      3  0.0      normal   No  
4        1.4      1  0.0      normal   No  
..       ...    ...  ...         ...  ...  
298      1.2      2  0.0  reversable  Yes  
299      3.4      2  2.0  reversable  Yes  
300      1.2      2  1.0  reversable  Yes  
301      0.0      2  1.0      normal  Yes  
302      0.0      1  NaN      normal   No  

[303 rows x 14 columns]

In [4]:
df["ChestPain"]=df["ChestPain"].astype("category")
df["ChestPain"]=df["ChestPain"].cat.codes

df["Thal"]=df["Thal"].astype("category")
df["Thal"]=df["Thal"].cat.codes

df["AHD"]=df["AHD"].astype("category")
df["AHD"]=df["AHD"].cat.codes

In [5]:
df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   
302   38    1          1     138   175    0        0    173      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0     0    0  
1        2  3.0     1    1  
2        2  2.0     2    1  
3        3  0.0     1    0  
4        1  0.0     1    0  
..     ...  ...   ...  ...  
298      2  0.0     2    1  
299      2  2.0     2    1  
300      2  1.0     2    1  
301      2  1.0     1    1  
302      1  NaN     1    0  

[303 rows x 14 columns]

In [6]:
df.isnull().sum()

Age          0
Sex          0
ChestPain    0
RestBP       0
Chol         0
Fbs          0
RestECG      0
MaxHR        0
ExAng        0
Oldpeak      0
Slope        0
Ca           4
Thal         0
AHD          0
dtype: int64

In [7]:
df=df.dropna()
df

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  AHD  
0        3  0.0     0    0  
1        2  3.0     1    1  
2        2  2.0     2    1  
3        3  0.0     1    0  
4        1  0.0     1    0  
..     ...  ...   ...  ...  
297      2  0.0     2    1  
298      2  0.0     2    1  
299      2  2.0     2    1  
300      2  1.0     2    1  
301      2  1.0     1    1  

[299 rows x 14 columns]

In [8]:
x=df.drop(columns="AHD")
x

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
0     63    1          3     145   233    1        2    150      0      2.3   
1     67    1          0     160   286    0        2    108      1      1.5   
2     67    1          0     120   229    0        2    129      1      2.6   
3     37    1          1     130   250    0        0    187      0      3.5   
4     41    0          2     130   204    0        2    172      0      1.4   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
297   57    0          0     140   241    0        0    123      1      0.2   
298   45    1          3     110   264    0        0    132      0      1.2   
299   68    1          0     144   193    1        0    141      0      3.4   
300   57    1          0     130   131    0        0    115      1      1.2   
301   57    0          2     130   236    0        2    174      0      0.0   

     Slope   Ca  Thal  
0        3  0.0     0  
1        2  3.0     1  
2        2  2.0     2  
3        3  0.0     1  
4        1  0.0     1  
..     ...  ...   ...  
297      2  0.0     2  
298      2  0.0     2  
299      2  2.0     2  
300      2  1.0     2  
301      2  1.0     1  

[299 rows x 13 columns]

In [9]:
y=df["AHD"]
y

0      0
1      1
2      1
3      0
4      0
      ..
297    1
298    1
299    1
300    1
301    1
Name: AHD, Length: 299, dtype: int8

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=10)

In [11]:
x_train

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
75    65    0          1     160   360    0        2    151      0      0.8   
211   38    1          3     120   231    0        0    182      1      3.8   
292   44    1          0     120   169    0        0    144      1      2.8   
188   54    1          2     192   283    0        2    195      0      0.0   
20    64    1          3     110   211    0        2    144      1      1.8   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
156   51    1          0     140   299    0        0    173      1      1.6   
123   55    1          0     140   217    0        0    111      1      5.6   
15    57    1          1     150   168    0        0    174      0      1.6   
125   45    0          2     130   234    0        2    175      0      0.6   
267   59    1          1     126   218    1        0    134      0      2.2   

     Slope   Ca  Thal  
75       1  0.0     1  
211      2  0.0     2  
292      3  0.0     0  
188      1  1.0     2  
20       2  0.0     1  
..     ...  ...   ...  
156      1  0.0     2  
123      3  0.0     2  
15       1  0.0     1  
125      2  0.0     1  
267      2  1.0     0  

[209 rows x 13 columns]

In [12]:
x_test

Age  Sex  ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  \
24    60    1          0     130   206    0        2    132      1      2.4   
64    54    1          0     120   188    0        0    113      0      1.4   
102   57    0          0     128   303    0        2    159      0      0.0   
171   53    1          0     142   226    0        2    111      1      0.0   
288   56    1          2     130   221    0        2    163      0      0.0   
..   ...  ...        ...     ...   ...  ...      ...    ...    ...      ...   
49    53    1          1     130   197    1        2    152      0      1.2   
275   64    1          3     170   227    0        2    155      0      0.6   
196   69    1          3     160   234    1        2    131      0      0.1   
58    54    1          1     125   273    0        2    152      0      0.5   
148   45    1          2     128   308    0        2    170      0      0.0   

     Slope   Ca  Thal  
24       2  2.0     2  
64       2  1.0     2  
102      1  1.0     1  
171      1  0.0     2  
288      1  0.0     2  
..     ...  ...   ...  
49       3  0.0     1  
275      2  0.0     2  
196      2  1.0     1  
58       3  1.0     1  
148      1  0.0     1  

[90 rows x 13 columns]

In [13]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [14]:
x_train

array([[ 1.11811957, -1.43997549,  0.16952178, ..., -0.95948164,
        -0.70400041, -0.49339355],
       [-1.78415676,  0.69445626,  2.25364243, ...,  0.61950783,
        -0.70400041,  1.14341997],
       [-1.13920646,  0.69445626, -0.87253855, ...,  2.19849731,
        -0.70400041, -2.13020706],
       ...,
       [ 0.25818584,  0.69445626,  0.16952178, ..., -0.95948164,
        -0.70400041, -0.49339355],
       [-1.03171475, -1.43997549,  1.2115821 , ...,  0.61950783,
        -0.70400041, -0.49339355],
       [ 0.47316928,  0.69445626,  0.16952178, ...,  0.61950783,
         0.36998562, -2.13020706]])

In [15]:
x_test

array([[ 0.58066099,  0.69445626, -0.87253855, ...,  0.61950783,
         1.44397165,  1.14341997],
       [-0.0642893 ,  0.69445626, -0.87253855, ...,  0.61950783,
         0.36998562,  1.14341997],
       [ 0.25818584, -1.43997549, -0.87253855, ..., -0.95948164,
         0.36998562, -0.49339355],
       ...,
       [ 1.54808644,  0.69445626,  2.25364243, ...,  0.61950783,
         0.36998562, -0.49339355],
       [-0.0642893 ,  0.69445626,  0.16952178, ...,  2.19849731,
         0.36998562, -0.49339355],
       [-1.03171475,  0.69445626,  1.2115821 , ..., -0.95948164,
        -0.70400041, -0.49339355]])

In [16]:
from sklearn.linear_model import LogisticRegression
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [17]:
y_train_pred=model.predict(x_train)
y_train_pred[:10]

array([0, 0, 1, 1, 0, 1, 0, 1, 0, 0], dtype=int8)

In [19]:
y_train[:10]

75     0
211    1
292    1
188    1
20     0
38     1
219    0
290    1
163    0
132    0
Name: AHD, dtype: int8

In [20]:
model.score(x_train,y_train)

0.8516746411483254

In [23]:
y_test_pred=model.predict(x_test)
y_test_pred[:10]

array([1, 1, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int8)

In [24]:
y_test[:10]

24     1
64     1
102    0
171    0
288    0
139    0
200    0
129    0
295    0
282    1
Name: AHD, dtype: int8

In [25]:
model.score(x_test,y_test)

0.8111111111111111